config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'lookup#search'

  post 'results' => 'lookup#results'

  get 'allcontacts' => 'contacts#index'

  resources :contacts

end

app/models/contact.rb
class Contact < ActiveRecord::Base
	mount_uploader :avatar, AvatarUploader

	belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

	has_many :contacts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

before_filter :authenticate_user!

before_action :configure_permitted_parameters, if: :devise_controller?

protected

	def configure_permitted_parameters
		devise_parameter_sanitizer.for(:sign_up) { |u| u.permit({ roles: [] }, :email, :password, :password_confirmation, :name) }

	  devise_parameter_sanitizer.for(:account_update) { |u| u.permit({ roles: [] }, :email, :password, :password_confirmation, :current_password, :name) }
	end


end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  before_action :set_contact, only: [:show, :edit, :update, :destroy]

  # GET /contacts
  # GET /contacts.json
  def index
    @contacts = Contact.where(user_id: current_user.id)
  end

  # GET /contacts/1
  # GET /contacts/1.json
  def show
  end

  # GET /contacts/new
  def new
    @contact = Contact.new
  end

  # GET /contacts/1/edit
  def edit
  end

  # POST /contacts
  # POST /contacts.json
  def create
    @contact = Contact.new(contact_params)

    respond_to do |format|
      if @contact.save
        format.html { redirect_to @contact, notice: 'Contact was successfully created.' }
        format.json { render :show, status: :created, location: @contact }
      else
        format.html { render :new }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /contacts/1
  # PATCH/PUT /contacts/1.json
  def update
    respond_to do |format|
      if @contact.update(contact_params)
        format.html { redirect_to @contact, notice: 'Contact was successfully updated.' }
        format.json { render :show, status: :ok, location: @contact }
      else
        format.html { render :edit }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contacts/1
  # DELETE /contacts/1.json
  def destroy
    @contact.destroy
    respond_to do |format|
      format.html { redirect_to contacts_url, notice: 'Contact was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_contact
      @contact = Contact.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def contact_params
      params.require(:contact).permit(:first_name, :last_name, :business_name, :address, :city, :state, :zip, :phone1, :phone2, :email, :avatar, :user_id)
    end
end

app/controllers/lookup_controller.rb
class LookupController < ApplicationController
  def search
  end

  def results
  	if params[:name] != nil
  		name_arr = params[:name].titleize.split
  		@results = Contact.where(first_name: name_arr[0], last_name: name_arr[1], user_id: current_user.id)
  	elsif params[:city] != nil
  		@results = Contact.where(city: params[:city].titleize, user_id: current_user.id)
    elsif params[:business_name] != nil
      @results = Contact.where(business_name: params[:business_name].titleize, user_id: current_user.id)
  	end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/lookup_helper.rb
module LookupHelper
end

app/views/contacts/_form.html.erb
<%= form_for(@contact) do |f| %>
  <% if @contact.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@contact.errors.count, "error") %> prohibited this contact from being saved:</h2>

      <ul>
      <% @contact.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.text_field :first_name, placeholder: "First Name" %>
<!--   </div>
  <div class="field"> -->
    <%= f.text_field :last_name, placeholder: "Last Name" %>
  </div>

  <br>
  <div class="field">
    <%= f.text_field :business_name, placeholder: "Business or Position" %>
  </div>
  <br>
  <div class="field">
    <%= f.text_field :address, placeholder: "Street Address" %>
  </div>
  <div class="field">
    <%= f.text_field :city, placeholder: "City" %>
<!--   </div>
  <div class="field"> -->
    <%= f.text_field :state, placeholder: "State" %>
 <!--  </div>
  <div class="field"> -->
    <%= f.text_field :zip, placeholder: "Zip Code" %>
  </div>
  <br>
  <div class="field">
    <%= f.text_field :phone1, placeholder: "Primary Phone #" %>
<!--   </div>
  <div class="field"> -->
    <%= f.text_field :phone2, placeholder: "Secondary Phone #" %>
  </div>
  <br>
  <div class="field">
    <%= f.text_field :email, placeholder: "Email Address" %>
  </div>
  <br>
  <div class="field">
    <strong> Upload Image: </strong>
    <%= f.file_field :avatar %>
  </div>
<br>
<br>
  <div>
    <%= f.hidden_field :user_id, value: current_user.id %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/contacts/edit.html.erb
<h1>Editing Contact</h1>

<%= render 'form' %>

<%= link_to 'Show', @contact %> |
<%= link_to 'Back', contacts_path %>

app/views/contacts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Contacts</h1>

<table class="table">
  <thead>
    <tr>
      <th>First Name</th>
      <th>Last Name</th>
      <th>Business Name</th>
      <th>Address</th>
      <th>City</th>
      <th>State</th>
      <th>Zip</th>
      <th>Phone 1</th>
      <th>Phone 2</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @contacts.each do |contact| %>
      <tr>
        <td><%= contact.first_name %></td>
        <td><%= contact.last_name %></td>
        <td><%= contact.business_name %></td>
        <td><%= contact.address %></td>
        <td><%= contact.city %></td>
        <td><%= contact.state %></td>
        <td><%= contact.zip %></td>
        <td><%= contact.phone1 %></td>
        <td><%= contact.phone2 %></td>
        <td><%= contact.email %></td>
        <td><%= link_to 'Show', contact %></td>
        <td><%= link_to 'Edit', edit_contact_path(contact) %></td>
        <td><%= link_to 'Destroy', contact, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/contacts/new.html.erb
<h1>New Contact</h1>

<%= render 'form' %>

<%= link_to 'Back', contacts_path %>

app/views/contacts/show.html.erb
<p id="notice"><%= notice %></p>

<div class="sm-container" >
  <!-- <div class ="center-it"> -->
    <p>
    <%= image_tag @contact.avatar.thumb.url, alt: "contact pic" %>
    </p>

    <p>
      <strong>Name:</strong>
      <%= @contact.first_name %> <%= @contact.last_name %>
    </p>


    <p>
      <strong>Business or Position:</strong>
      <%= @contact.business_name %>
    </p>


    <p>
      <strong>Address:</strong>
      <%= @contact.address %> <br>
      <%= @contact.city %>, <%= @contact.state %> <%= @contact.zip %>
    </p>



    <p>
      <strong>Primary / Secondary Phones:</strong>
      <%= @contact.phone1 %> / <%= @contact.phone2 %>
    </p>


    <p>
      <strong>Email:</strong>
      <%= @contact.email %>
    </p>
  </div>
<!-- </div> -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ContactBook</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
 <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

<%= stylesheet_link_tag "https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css", integrity: "sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7", crossorigin:"anonymous" %>

  <!-- Latest compiled and minified JavaScript -->
  <%= javascript_include_tag "https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js", integrity: "sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS", crossorigin:"anonymous" %>


</head>
<body>
 
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Look Up", root_path, class: "navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to "All Contacts", allcontacts_path %></li>
        <li><%= link_to "Create New Contact", new_contact_path %></li>
        
      </ul>
     
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
          <li><%= link_to "Welcome, #{current_user.name}!", root_path %> </li>
          <li><%= link_to "Edit Profile", edit_user_registration_path %></li>
          <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
        <% end %>
        
      </ul>

    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>






<div class="container">
	<%= yield %>
</div>


</body>
</html>

app/views/lookup/results.html.erb
<div class="center-it">

<h1>Search Results</h1>
</div>


<br>
<ul>
	<% @results.each do |result| %>
		<li><%= "#{result.first_name} #{result.last_name}, #{result.business_name}" %> <br>
			<%="#{result.address}; #{result.city}, #{result.state}, #{result.zip}" %> <br>
			<%= "#{result.email}, #{result.phone1} / #{result.phone2}" %>
		</li>
		<br>
	<% end %>

</ul>

app/views/lookup/search.html.erb
<style>
.center-it { text-align: center}
</style>

<div class="center-it">
	<h1><u>Look Up a Contact </u></h1>

	<%= form_tag(results_path) do %>
		<div class="form-group">
			<%= text_field_tag :name, nil, placeholder: "By First & Last Name", class: "form control" %>
		<!-- </div>
		<div class="form-group"> -->
			<%= submit_tag "Search", class: "btn btn-default" %>
		</div>
		<% end %>


<%= form_tag(results_path) do %>
	<div class="form-group">
		<%=text_field_tag :business_name, nil, placeholder: "By Business or Position", class: "form control" %>
		<%= submit_tag "Search", class: "btn btn-default" %>
		</div>

<% end %>

<%= form_tag(results_path) do %>
	<div class="form-group">
		<%=text_field_tag :city, nil, placeholder: "By City", class: "form control" %>
		<%= submit_tag "Search", class: "btn btn-default" %>
		</div>
	</div>
<% end %>


	</div>